import { GenerateContentParameters, GenerateContentResponse, GoogleGenAI } from '@google/genai';
import Tags from '../utils/Tags.js';
import { execSync } from "child_process";
import { GetDiffContentProp, GoogleAIModels } from '../types/CommitAITypes.js';
import humanNumber from "human-number"

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const callerPath = process.env.CALL_FROM
const showAIWatermark: boolean = true

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

console.log(`[${Tags.System}] Generative Commit Message`)
console.log(`[${Tags.System}] Called From: ${callerPath}`)

const AI_MODEL: GoogleAIModels = "gemini-2.5-flash-lite"

async function summaryWithAI(gitDiffMsg: string) {
    const promt = `
    You are a commit-message generator. Read the provided git diff HEAD and produce a concise 50-character (max) summary and a detailed commit description broken into individual change lines. Output must be exactly one JSON array of strings and nothing else.
    
    Rules & format:
    - Output only a JSON array of strings. Example: ["<subject>", "- <type>(<scope>): <short desc>", "- <type>(<scope>): <short desc>",]
    - Element 0 — subject: one line, ≤150 characters, terse summary (use imperative tone).
    - Elements 1..N — body lines: one change per line, each MUST start with - and follow conventional prefix:
    - type(scope): short description where type ∈ {feat, fix, docs, style, refactor, perf, test, chore, ci, build, revert}. Use scope when meaningful (e.g., links, posts, ws, uac).
    - Use imperative, present-tense verbs and concise phrasing. Each body line should be a single sentence-like fragment (avoid commas that create multi-sentence lines).
    - If multiple unrelated changes exist, produce separate lines for each feature/area. If many small fixes occurred in one area, coalesce into logical, single-line items per feature.
    - Keep each body line short (preferably ≤ 80 chars). Avoid filler words.
    - If the diff shows no changes, return ["No changes"].
    - Do not output anything other than the JSON array (no logs, explanation, or markdown) including starting & ending code block (\`\`\`json). Just output pure array.

    Mapping examples (for your reference; not to be output):
    - fix(links): update links return limit error
    - refactor(posts): remove unnecessary code accessing post
    - feat(ws): add new ws handler
    - test(uac): add user creation access token (WIP).

    Now, read the diff that follows and output only the JSON array as specified.

    [Start of git head diff content]
    
    ${gitDiffMsg}
    
    [End of gir head diff content]
    `

    const aiConfig: GenerateContentParameters = {
        model: AI_MODEL,
        contents: promt
    }

    console.log(`[${Tags.AI}] Initialized Google Gemini via API. Using Model: ${aiConfig.model}.`)
    
    if (showAIWatermark) {
        console.log(`[${Tags.AI}] Showing AI Watermark in the end of commit message.`)
    }
    
    console.log(`[${Tags.AI}] Sending promt.. Waiting for response..`)

    const startTime = Date.now()

    const response = await ai.models.generateContent(aiConfig);

    const endsTime = Date.now()

    console.log(`[${Tags.AI}] Elapsed ${endsTime - startTime}ms.`)

    const res = response.text

    if (!res) {
        console.log(`[${Tags.AI}] AI Didn't send any response.`)
        return { data: [] }
    }

    console.log("")

    const cleanedRes = res.replace("\`\`\`json", "").replace("\`\`\`", "")

    let data: string[] = JSON.parse(cleanedRes)
    console.log(`[${Tags.AI}] Cleaned Response:`)

    for (let i = 0; i < data.length; i++) {
        const res = data[i];
        console.log(`[${Tags.AI}] ${res.replace(/"/g, "")}`)
    }

    console.log("")

    return { data, response }
}

async function writeCommitMessage(changes: string[], response?: GenerateContentResponse) {
    if (!changes || changes.length == 0) {
        console.log(`[${Tags.Git}] Didn't receive string array of changes.`)
        return 
    }

    let changesMessages = ""
    const title = changes[0]

    for (let i = 1; i < changes.length; i++) {
        const msg = changes[i];
        changesMessages += `${msg}\n`
    }

    const totalTokenRaw = response?.usageMetadata?.totalTokenCount ?? 0
    const totalTokenFormatted = humanNumber(totalTokenRaw)
    
    if (showAIWatermark) changesMessages += `✨ Automatically Generated by Google Gemini (${response?.modelVersion ?? "Unknown Model"}, wasted ${totalTokenFormatted} tokens)`

    const commands = [
        "git add .",
        "git commit " + `-m "${title}" -m "${changesMessages}"`,
        "git push"
    ]

    // exec on callerPath
    for (let i = 0; i < commands.length; i++) {
        const res = commands[i];
        try {
            console.log(`[${Tags.Git}] Running: ${res}`)
            execSync(res, { cwd: callerPath, stdio: "inherit" });
        } catch (e) {
            console.log(`[${Tags.Error}] Failed to run git command [${res}]`)
            console.error(e)
            return false
        }
    }
    

    return true
}

async function getDiffContent() {
    let output = null

    try {
        output = execSync("git diff HEAD", {
            cwd: callerPath,
            stdio: "pipe",
            encoding: "utf-8",
        });
    } catch (e: any) {
        const msg = e.message as string
        if (msg.includes("Not a git repository")) {
            return { error: "not_in_repository"} as GetDiffContentProp
        }
    }

    return { data: output } as GetDiffContentProp
}

const gitDiffContent = await getDiffContent()

if (gitDiffContent?.error == "not_in_repository") {
    console.log(`[${Tags.Error}] Couldn't find Git Repository on ${callerPath}.`)
    console.log(`[${Tags.Error}] Make sure you have inited github repo there.`)
    process.exit(1)
}

if (gitDiffContent.data.length == 0) {
    console.log(`[${Tags.Error}] There is no diff message there..`)
    process.exit(1)
}

if (gitDiffContent.data) {
    console.log(`[${Tags.System}] Found ${gitDiffContent.data.length} line${gitDiffContent.data.length > 1 ? "s" : ""} of changes.`)
    
    const { data: changesMessage, response } = await summaryWithAI(gitDiffContent.data)
    const gitAction = await writeCommitMessage(changesMessage, response)

    if (gitAction == false) {
        console.log(`[${Tags.Git}] Finished with error. [SUCCESS]`)
    } else {
        console.log(`[${Tags.Git}] Finished with no error. [FAILED]`)
    }
} else {
    console.log(`[${Tags.Error}] getDiffContent returns no data.`)
    process.exit(1)
}