import { execSync } from "child_process";
import humanNumber from "human-number";
import notifier from 'node-notifier';
import { type SummaryGitChangesStatsResponse } from "../gemini/GeminiService.js";
import Tags from "../utils/Tags.js";
import path from "path";
import fs from "fs";

interface GetRepoDiffContentProp {
    projectDir: string;
}

export interface GetRepoDiffContentResponse {
    data: string | null;
    error?: "not_in_repository";
}

interface SendNotificationProp {
    message: string
    timeout?: number
}

interface WriteCommitMessageProp {
    projectDir: string;
    changes: string[]
    stats: SummaryGitChangesStatsResponse
    showAIWatermark?: boolean
}

interface WriteCommitMessageResponse {
    success: boolean;
    elapsed?: number
    error?: "execute_failed"
}

const commitAIFilename = ".commitai"

export function CommitAIService() {
    const services = {
        // Create CommitAI Identifier file.
        // for identifying project, ofc.
        CreateIdentifierFile: async (projectDir: string): Promise<boolean> => {
            const commitAIIdentifierFIle = path.join(projectDir, commitAIFilename);
            try {
                const uuid = crypto.randomUUID()
                await fs.writeFileSync(commitAIIdentifierFIle, `${uuid}`);
                console.log(`[${Tags.System}] Created new CommitAI Identifier: ${uuid}`)
                return true
            } catch {
                return false
            }
        },
        // Check if project's .gitignore already have ".commitai" added or not.
        // If not, add. that simple.
        DoTheGitignoreFile: async (projectDir: string) => {
            const gitignorePath = path.join(projectDir, ".gitignore");
            const gitIgnoreFileExists = fs.existsSync(gitignorePath)

            if (gitIgnoreFileExists) {
                const content = fs.readFileSync(gitignorePath, "utf-8")

                // split by newlines
                const splitted = content?.split("\n")

                const found = splitted?.filter((x) => x == commitAIFilename)

                if (found.length == 0) {
                    const addition = `\n# This line was added by CommitAI.\n${commitAIFilename}`
                    
                    await fs.appendFileSync(gitignorePath, addition)
                    
                    console.log(`[${Tags.System}] Added ${commitAIFilename} into .gitignore file..`)
                }
            } else {
                console.log(`[${Tags.Debug}] no gitignore file`)
            }
        },
        // This thing is for sending notification.
        SendDesktopNotification: ({ message, timeout }: SendNotificationProp) => {
            notifier.notify({
                title: 'CommitAI',
                message,
                sound: true,
                wait: true,
                timeout: timeout ?? 5
            });
        },
        // Parses project's repo diff content
        GetRepoDiffContent: async ({ projectDir }: GetRepoDiffContentProp): Promise<GetRepoDiffContentResponse> => {
            let data = null

            await CommitAIService().DoTheGitignoreFile(projectDir);

            try {
                data = execSync("git diff HEAD --no-ext-diff", {
                    cwd: projectDir,
                    stdio: "pipe",
                    encoding: "utf-8",
                });
            } catch (e: any) {
                const msg = e?.message as string
                if (msg.includes("Not a git repository")) {
                    return { data: null, error: "not_in_repository" }
                }
            }

            return { data }
        },
        // This handle pushing the summarize to git.
        WriteCommitMessage: async ({ projectDir, changes, stats, showAIWatermark }: WriteCommitMessageProp): Promise<WriteCommitMessageResponse> => {
            if (!changes || changes.length == 0) {
                console.log(`[${Tags.Git}] Didn't receive string array of changes.`)
                return { success: false, elapsed: 0 }
            }

            const startTime = Date.now()

            let changesMessages = ""
            const title = changes[0]

            for (let i = 1; i < changes.length; i++) {
                const msg = changes[i];
                changesMessages += `${msg}\n`
            }

            const { modelVersion, usageMetadata } = stats
            const totalTokenRaw = usageMetadata?.totalTokenCount ?? 0
            const totalTokenFormatted = humanNumber(totalTokenRaw)

            if (showAIWatermark) changesMessages += `✨ Automatically Generated by Google Gemini (${modelVersion ?? "Unknown Model"}, wasted ${totalTokenFormatted} tokens)`

            const commands = [
                "git add .",
                "git commit " + `-m "${title}" -m "${changesMessages}"`,
                "git push"
            ]

            // exec on callerPath
            for (let i = 0; i < commands.length; i++) {
                const res = commands[i];

                if (!res) continue;

                try {
                    console.log(`[${Tags.Git}] Running: ${res}`)
                    execSync(res, { cwd: projectDir, stdio: "inherit" });
                } catch (e) {
                    console.log(`[${Tags.Error}] Failed to run git command [${res}]`)
                    console.error(e)
                    return { success: false, error: "execute_failed" }
                }
            }

            const endTime = Date.now()
            const elapsed = endTime - startTime
            return { success: true, elapsed }
        }
    }

    return services
}