import { GenerateContentParameters, GoogleGenAI } from '@google/genai';
import { execSync } from "child_process";
import humanNumber from "human-number";
import notifier from 'node-notifier';
import { AIPersonality, GetDiffContentResponse, GoogleAIModels, SummaryWithAIProp, SummaryWithAIResponse, WriteCommitMessageProp } from '../types/CommitAITypes.js';
import Tags from '../utils/Tags.js';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const callerPath = process.env.CALL_FROM
const showAIWatermark: boolean = false

const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });

console.log(`[${Tags.System}] Generative Commit Message`)
console.log(`[${Tags.System}] Called From: ${callerPath}`)

const AI_MODEL: GoogleAIModels = "gemini-2.5-flash-lite"
const selectedPersonality: AIPersonality = "normal"

interface SendNotificationProp {
    message: string
}

async function sendNotification({ message }: SendNotificationProp): Promise<void> {
    notifier.notify({
        title: 'CommitAI',
        message,
        sound: true,
        wait: true,
        timeout: 5
    });
    
}


async function summaryWithAI({ gitDiffMessage, personality }: SummaryWithAIProp): Promise<SummaryWithAIResponse> {
    let promts =  (await import("./promts.json")).default
    let selectedPromt = null

    console.log(`[${Tags.AI}] Selected Personality: ${personality}`)

    if (personality == "normal") {
        selectedPromt = promts["normal_prompt"]
    } else if (personality == "sarcastic") {
        selectedPromt = promts["sarcastic_prompt"]
    } else if (personality == "toxic") {
        selectedPromt = promts["toxic_prompt"]
    } else if (personality == "tsundere") {
        selectedPromt = promts["tsundere_prompt"]
    } else if (personality == "random") {
        const picker = Math.floor(Math.random() * AIPersonality.length)
        const choosen = AIPersonality[picker]

        summaryWithAI({ gitDiffMessage, personality: choosen })
    } else {
        return { data: [], response: null }
    }

    const promt = `
    ${selectedPromt}

    [Start of git head diff content]
    
    ${gitDiffMessage}
    
    [End of gir head diff content]
    `

    const aiConfig: GenerateContentParameters = {
        model: AI_MODEL,
        contents: promt
    }

    console.log(`[${Tags.AI}] Initialized Google Gemini via API. Using Model: ${aiConfig.model}.`)
    
    if (showAIWatermark) {
        console.log(`[${Tags.AI}] Showing AI Watermark in the end of commit message.`)
    }
    
    console.log(`[${Tags.AI}] Sending promt.. Waiting for response..`)

    const startTime = Date.now()

    const response = await ai.models.generateContent(aiConfig);

    const endsTime = Date.now()

    console.log(`[${Tags.AI}] Elapsed ${endsTime - startTime}ms.`)

    const res = response.text

    if (!res) {
        console.log(`[${Tags.AI}] AI Didn't send any response.`)
        sendNotification({ message: "AI didn't send any response." })
        return { data: [], response: null }
    }

    console.log("")

    const cleanedRes = res.replace("\`\`\`json", "").replace("\`\`\`", "")

    let data: string[] = JSON.parse(cleanedRes)

    if (!data || data.length == 0) {
        console.log(`[${Tags.AI}] AI response is empty or not an array.`)
        console.log(data)
        sendNotification({ message: "AI response is empty or not an array. Please check the logs for more details." })
        return { data: [], response }
    }

    console.log(`[${Tags.AI}] Cleaned Response:`)

    for (let i = 0; i < data.length; i++) {
        const res = data[i];
        console.log(`[${Tags.AI}] ${res.replace(/"/g, "")}`)
    }

    console.log("")

    return { data, response }
}

async function writeCommitMessage({ changes, response }: WriteCommitMessageProp): Promise<boolean> {
    if (!changes || changes.length == 0) {
        console.log(`[${Tags.Git}] Didn't receive string array of changes.`)
        return false
    }

    let changesMessages = ""
    const title = changes[0]

    for (let i = 1; i < changes.length; i++) {
        const msg = changes[i];
        changesMessages += `${msg}\n`
    }

    const totalTokenRaw = response?.usageMetadata?.totalTokenCount ?? 0
    const totalTokenFormatted = humanNumber(totalTokenRaw)
    
    if (showAIWatermark) changesMessages += `✨ Automatically Generated by Google Gemini (${response?.modelVersion ?? "Unknown Model"}, wasted ${totalTokenFormatted} tokens)`

    const commands = [
        "git add .",
        "git commit " + `-m "${title}" -m "${changesMessages}"`,
        "git push"
    ]

    // exec on callerPath
    for (let i = 0; i < commands.length; i++) {
        const res = commands[i];
        try {
            console.log(`[${Tags.Git}] Running: ${res}`)
            execSync(res, { cwd: callerPath, stdio: "inherit" });
        } catch (e) {
            console.log(`[${Tags.Error}] Failed to run git command [${res}]`)
            console.error(e)
            sendNotification({ message: `Failed to run git command [${res}]. Please check the logs for more details.` })
            return false
        }
    }
    
    return true
}

async function getDiffContent(): Promise<GetDiffContentResponse> {
    let output = null

    try {
        output = execSync("git diff HEAD", {
            cwd: callerPath,
            stdio: "pipe",
            encoding: "utf-8",
        });
    } catch (e: any) {
        const msg = e.message as string
        if (msg.includes("Not a git repository")) {
            return { data: null, error: "not_in_repository"}
        }
    }

    return { data: output } 
}

const gitDiffContent = await getDiffContent()

if (gitDiffContent?.error == "not_in_repository") {
    console.log(`[${Tags.Error}] Couldn't find Git Repository on ${callerPath}.`)
    console.log(`[${Tags.Error}] Make sure you have inited github repo there.`)
    process.exit(1)
}

if (gitDiffContent.data && gitDiffContent.data.length == 0) {
    console.log(`[${Tags.Error}] There is no diff message there..`)
    process.exit(1)
}

if (gitDiffContent.data) {
    console.log(`[${Tags.System}] Found ${gitDiffContent.data.length} line${gitDiffContent.data.length > 1 ? "s" : ""} of changes.`)
    
    const { data: changesMessage, response } = await summaryWithAI({ gitDiffMessage: gitDiffContent.data, personality: selectedPersonality })
    const gitAction = await writeCommitMessage({ changes: changesMessage, response })

    if (gitAction == false) {
        console.log(`[${Tags.Git}] Finished with error. [FAILED]`)
    } else {
        console.log(`[${Tags.Git}] Finished with no error. [SUCCESS]`)
        sendNotification({ message: `👍. Wasted ${response?.usageMetadata?.totalTokenCount ?? 0} tokens.` })
    }
} else {
    console.log(`[${Tags.Error}] getDiffContent returns no data.`)
    console.log(gitDiffContent)
    process.exit(1)
}